/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package thuy;

import dao.danhmucdongvatDao;
import dao.danhsachdongvatDao;
import entity.danhmucdongvat;
import entity.danhsachdongvat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import uliti.Dialog;

/**
 *
 * @author Hieu
 */
public class QLDanhSach extends javax.swing.JDialog {
    int row = -1;
    boolean isValidate = false;
    List<danhmucdongvat> lstdm = new ArrayList<>();
    List<danhsachdongvat> lstdv = new ArrayList<>();
    public danhmucdongvatDao dmdao;
    public danhsachdongvatDao dsdao;

    /**
     * Creates new form danhsachdongvat
     */
    public QLDanhSach(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        dmdao = new danhmucdongvatDao();
        dsdao = new danhsachdongvatDao();
        filltable();
        fillCbb();
    }
    public void moi() {
        txt_CanNang.setText("");
        txt_GhiChu.setText("");
        txt_MaDV.setText("");
        txt_MaDV.setText("");
        cbb_DanhMuc.setSelectedIndex(0);
    }
    public void fillCbb(){
        lstdm = dmdao.getAllData();
        cbb_DanhMuc.removeAllItems();
        for (danhmucdongvat object : lstdm) {
            cbb_DanhMuc.addItem(object.getTendm());
        }
    }
    public int getIDDm(){
        int index = cbb_DanhMuc.getSelectedIndex();
        lstdm = dmdao.getAllData();
        danhmucdongvat a = lstdm.get(index);
        return a.getId();
    }
    public void add() {
        danhsachdongvat a = getForm();
        if (!isValidate) {
            return;
        }
        dsdao.addData(a);
        filltable();
    }
//
    public void sua() {
        if (row < 0) {
            Dialog.mess("Vui Lòng Chọn Trường Dữ Liệu Để Thao Tác");
            return;
        }
        danhsachdongvat a = getForm();
        if (!isValidate) {
            return;
        }
        dsdao.updateData(a);
        filltable();
    }
//
    public void xoa() {
        if (row < 0) {
            Dialog.mess("Vui Lòng Chọn Trường Dữ Liệu Để Thao Tác");
            return;
        }
        danhsachdongvat a = getForm();
        dsdao.deleteData(a);
        filltable();
    }
//
    public danhsachdongvat getForm() {
        row = tbl_DongVat.getSelectedRow();
        danhsachdongvat a = new danhsachdongvat();
        if (row != -1) {
            int id = (int) tbl_DongVat.getValueAt(row, 0);
            a.setId(id);
        }
        String madv = txt_MaDV.getText();
        String iddv = String.valueOf(getIDDm());
        String Tendv = txt_TenDV.getText();
        String cannangstr = txt_CanNang.getText();
        String ghiChu = txt_GhiChu.getText();
        String[] strs = {madv,iddv,Tendv,cannangstr,ghiChu};
        isValidate = uliti.validate.Validate(strs, 5);
        a.setMadv(madv);
        a.setId_danhmuc(getIDDm());
        a.setTendv(Tendv);
        try {
            float cannang = Float.parseFloat(cannangstr);
            a.setCannang(cannang);
        } catch (Exception e) {
        }
        a.setGhichu(ghiChu);
        return a;
    }
//
    public void setForm(int index) {
        lstdv = dsdao.getAllData();
        if (lstdv.isEmpty()) {
            System.out.println("Danh Sách Trống");
            return;
        }
        danhsachdongvat a = lstdv.get(index);
        txt_MaDV.setText(a.getMadv());
        txt_TenDV.setText(a.getTendv());
        txt_CanNang.setText(String.valueOf(a.getCannang()));
        txt_GhiChu.setText(a.getGhichu());
        cbb_DanhMuc.setSelectedItem(a.getTendm());
    }

    public void filltable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_DongVat.getModel();
        defaultTableModel.setRowCount(0);
        lstdv = dsdao.getAllData();
        if (lstdv.isEmpty()) {
            System.out.println("Danh Sách Trống");
            return;
        }
        int i = 0;
        for (danhsachdongvat object : lstdv) {
            i++;
            Object[] row = {
                object.getId(),
                object.getMadv(),
                object.getTendm(),
                object.getTendv(),
                object.getCannang(),
                object.getTrangthai() == 1 ? "Tạm Chưa Nghĩ Ra" : "aa"
            };
            defaultTableModel.addRow(row);
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DongVat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_MaDV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_TenDV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_CanNang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_GhiChu = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cbb_DanhMuc = new javax.swing.JComboBox<>();
        btn_Them = new javax.swing.JButton();
        btn_moi = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_DongVat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã DV", "Tên Dm", "Tên DV", "Cân Nặng", "Trạng Thái"
            }
        ));
        tbl_DongVat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DongVatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_DongVat);

        jLabel1.setText("Mã DV");

        jLabel2.setText("Tên DV");

        jLabel3.setText("Cân nặng");

        jLabel4.setText("Ghi Chú");

        txt_GhiChu.setColumns(20);
        txt_GhiChu.setRows(5);
        jScrollPane2.setViewportView(txt_GhiChu);

        jLabel5.setText("Danh Mục");

        cbb_DanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txt_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txt_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txt_CanNang, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane2)
                        .addComponent(jLabel5)
                        .addComponent(cbb_DanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Them)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sua)
                        .addGap(18, 18, 18)
                        .addComponent(btn_xoa))
                    .addComponent(btn_moi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_CanNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_DanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them)
                            .addComponent(btn_sua)
                            .addComponent(btn_xoa))
                        .addGap(18, 18, 18)
                        .addComponent(btn_moi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        add();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        sua();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void tbl_DongVatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DongVatMouseClicked
        // TODO add your handling code here:
        row = tbl_DongVat.getSelectedRow();
        setForm(row);
    }//GEN-LAST:event_tbl_DongVatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDanhSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLDanhSach dialog = null;
                try {
                    dialog = new QLDanhSach(new javax.swing.JFrame(), true);
                } catch (Exception ex) {
                    Logger.getLogger(QLDanhSach.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbb_DanhMuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_DongVat;
    private javax.swing.JTextField txt_CanNang;
    private javax.swing.JTextArea txt_GhiChu;
    private javax.swing.JTextField txt_MaDV;
    private javax.swing.JTextField txt_TenDV;
    // End of variables declaration//GEN-END:variables
}
