/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package thuy;

import dao.danhsachdongvatDao;
import dao.lichsutiemphongDao;
import entity.danhmucdongvat;
import entity.danhsachdongvat;
import entity.lichsutiemphong;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import uliti.Dialog;

/**
 *
 * @author Hieu
 */
public class QLLichSu extends javax.swing.JDialog {

    List<lichsutiemphong> lstls;
    List<danhsachdongvat> lstds;
    lichsutiemphongDao daols;
    danhsachdongvatDao daods;
    int row = -1;
    boolean isvalidate = false;

    /**
     * Creates new form lichsutiemphongJDialog
     */
    public QLLichSu(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        daols = new lichsutiemphongDao();
        daods = new danhsachdongvatDao();
        fillCbb();
        filltable();
    }

    public void moi() {
        txt_mals.setText("");
        txt_loaibenh.setText("");
        txt_ngaytiem.setText("");
        cbb_Dv.setSelectedIndex(0);
    }

    public void fillCbb() {
        lstds = daods.getAllData();
        cbb_Dv.removeAllItems();
        for (danhsachdongvat object : lstds) {
            cbb_Dv.addItem(object.getTendv());
        }
    }

    public int getIDDv() {
        int index = cbb_Dv.getSelectedIndex();
        lstds = daods.getAllData();
        danhsachdongvat a = lstds.get(index);
        return a.getId();
    }

    public void add() throws ParseException {
        lichsutiemphong a = getForm();
        if (!isvalidate) {
            return;
        }
        daols.addData(a);
        filltable();
    }
//

    public void sua() throws ParseException {
        if (row < 0) {
            Dialog.mess("Vui Lòng Chọn Trường Dữ Liệu Để Thao Tác");
            return;
        }
        lichsutiemphong a = getForm();
        if (!isvalidate) {
            return;
        }
        daols.updateData(a);
        filltable();
    }
//

    public void xoa() throws ParseException {
        if (row < 0) {
            Dialog.mess("Vui Lòng Chọn Trường Dữ Liệu Để Thao Tác");
            return;
        }
        lichsutiemphong a = getForm();
        daols.deleteData(a);
        filltable();
    }
//

    public lichsutiemphong getForm() throws ParseException {
        row = tbl_ls.getSelectedRow();
        lichsutiemphong a = new lichsutiemphong();
        if (row != -1) {
            int id = (int) tbl_ls.getValueAt(row, 0);
            a.setId(id);
        }
        String mals = txt_mals.getText();
        String Id_dongvat = String.valueOf(getIDDv());
        String Loaibenh = txt_loaibenh.getText();
        String Ngaytiem = txt_ngaytiem.getText();
        String[] strs = {mals, Id_dongvat, Loaibenh, Ngaytiem};
        isvalidate = uliti.validate.Validate(strs, 4);
        a.setMals(mals);
        a.setId_dongvat(getIDDv());
        a.setLoaibenh(Loaibenh);
        try {
            a.setNgaytiem(uliti.DateUliti.stringToDate(Ngaytiem, "dd/MM/yyyy"));
        } catch (Exception e) {
        }
        return a;
    }
//

    public void setForm(int index) {
        lstls = daols.getAllData();
        if (lstls.isEmpty()) {
            System.out.println("Danh Sách Trống");
            return;
        }
        lichsutiemphong a = lstls.get(index);
        txt_mals.setText(a.getMals());
        txt_loaibenh.setText(a.getLoaibenh());
        txt_ngaytiem.setText(uliti.DateUliti.dateToString(a.getNgaytiem(), "dd/MM/yyyy"));
        cbb_Dv.setSelectedItem(a.getTendv());
    }

    public void filltable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_ls.getModel();
        defaultTableModel.setRowCount(0);
        lstls = daols.getAllData();
        if (lstls.isEmpty()) {
            System.out.println("Danh Sách Trống");
            return;
        }
        int i = 0;
        for (lichsutiemphong object : lstls) {
            i++;
            Object[] row = {
                object.getId(),
                object.getMals(),
                object.getTendv(),
                object.getLoaibenh(),
                object.getNgaytiem(),
                object.getTrangthai() == 1 ? "Tạm Chưa Nghĩ Ra" : "aa"
            };
            defaultTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_mals = new javax.swing.JTextField();
        txt_loaibenh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_ngaytiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbb_Dv = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ls = new javax.swing.JTable();
        btn_moi = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã LS");

        jLabel2.setText("Loại Bệnh");

        jLabel3.setText("Ngày Tiêm");

        jLabel4.setText("Tên ĐV");

        cbb_Dv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl_ls.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã LS", "Tên Đv", "Loại Bệnh", "Ngày Tiêm", "Trạng Thái"
            }
        ));
        tbl_ls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ls);

        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txt_mals)
                        .addComponent(jLabel2)
                        .addComponent(txt_loaibenh, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(txt_ngaytiem, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(cbb_Dv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Them)
                        .addGap(18, 18, 18)
                        .addComponent(btn_sua)
                        .addGap(18, 18, 18)
                        .addComponent(btn_xoa))
                    .addComponent(btn_moi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_loaibenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ngaytiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbb_Dv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them)
                            .addComponent(btn_sua)
                            .addComponent(btn_xoa))
                        .addGap(18, 18, 18)
                        .addComponent(btn_moi)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        try {
            // TODO add your handling code here:
            add();
        } catch (ParseException ex) {
            Logger.getLogger(QLLichSu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            // TODO add your handling code here:
            sua();
        } catch (ParseException ex) {
            Logger.getLogger(QLLichSu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            // TODO add your handling code here:
            xoa();
        } catch (ParseException ex) {
            Logger.getLogger(QLLichSu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void tbl_lsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lsMouseClicked
        // TODO add your handling code here:
        row = tbl_ls.getSelectedRow();
        setForm(row);
    }//GEN-LAST:event_tbl_lsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLLichSu dialog = null;
                try {
                    dialog = new QLLichSu(new javax.swing.JFrame(), true);
                } catch (Exception ex) {
                    Logger.getLogger(QLLichSu.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbb_Dv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_ls;
    private javax.swing.JTextField txt_loaibenh;
    private javax.swing.JTextField txt_mals;
    private javax.swing.JTextField txt_ngaytiem;
    // End of variables declaration//GEN-END:variables
}
